# Generated by Django 2.2.12 on 2020-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='f48g4hw',
            field=models.DateField(blank=True, null=True),
        ),
    ]
